# Generated by Django 5.1.1 on 2025-04-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0002_reparacion_costo_cotizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='costo_estimado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
