# Generated by Django 5.1.1 on 2025-04-29 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miApp', '0003_alter_cotizacion_costo_estimado'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=5, max_digits=10)),
                ('fecha_pago', models.DateField()),
                ('aprobacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metodo_pago', to='miApp.aprobacion')),
            ],
        ),
    ]
